name: CI/CD

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    container: joshkeegan/dotnet-mixed-build:5.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        working-directory: build
        run: make build
      
      - name: Run Unit Tests
        working-directory: build
        run: make unit-tests-run

      - name: Create Nuget Packages
        working-directory: build
        run: make nuget-create
      
      - name: Upload artefacts
        uses: actions/upload-artifact@v2
        with:
          name: artefacts
          path: artefacts
        if: ${{ always() }}
      
      - name: Upload deployment scripts
        uses: actions/upload-artifact@v2
        with:
          name: deploy
          path: deploy
      
      - name: Parse Test Results
        uses: NasAmin/trx-parser@v0.1.1
        with:
          TRX_PATH: artefacts/testResults
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
  
  cd:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:5.0.300-buster-slim
    needs: ci
    if: github.ref == 'refs/heads/release'
    steps:
      - name: Download deployment scripts
        uses: actions/download-artifact@v2
        with:
          name: deploy
          path: deploy
      
      - name: Download artefacts
        uses: actions/download-artifact@v2
        with:
          name: artefacts
          path: artefacts

      - name: Release
        working-directory: deploy
        run: /bin/bash deploy.sh ${{ secrets.NUGET_API_KEY }}